import vecteurForme
ShadyFox2004/Antoine-M_Boudreau_-_Tp1 pull request #15
Opened 2022-03-07 01:56 UTC by WildSource

review pls

2022-03-07 02:02 UTC, ShadyFox2004 commented on src/jeu/JeuMemoire.java
> +     * Vecteur Forme
Ajouter attributs au début du commentaire:
` * Attributs Vecteur Forme`

2022-03-07 02:08 UTC, ShadyFox2004 requested changes
Need more changes before being merge into the main tree

2022-03-07 02:08 UTC, ShadyFox2004 commented on src/jeu/JeuMemoire.java
> +            }
met des break.
Ou utilise des if.

2022-03-07 02:08 UTC, ShadyFox2004 commented on src/jeu/JeuMemoire.java
> +                for (int i = 0; i < 5; i++)
mettre un seul for avec une variable pour le niveau

2022-03-07 02:08 UTC, ShadyFox2004 commented on src/jeu/JeuMemoire.java
> +            case 4:
met des break.
Ou utilise des if.

2022-03-07 02:08 UTC, ShadyFox2004 commented on src/jeu/JeuMemoire.java
> +            }
met des break.
Ou utilise des if.

2022-03-07 02:08 UTC, ShadyFox2004 commented on src/jeu/JeuMemoire.java
> +            case 6:
met des break.
Ou utilise des if.

2022-03-07 02:08 UTC, ShadyFox2004 commented on src/jeu/JeuMemoire.java
> +        return null;
Faire le toString

2022-03-07 02:08 UTC, ShadyFox2004 commented on src/jeu/JeuMemoire.java
> +     * Todo
Ajoute ce que tu doit faire sur le todo

2022-03-07 02:08 UTC, ShadyFox2004 commented on src/jeu/JeuMemoire.java
> +     * Todo
`// TODO faire le toString`

2022-03-07 02:24 UTC, ShadyFox2004 submitted a review, later dismissed
Just get it done

2022-03-08 18:47 UTC, WildSource reviewed
class technically done need review and refactor and debugging

2022-03-08 23:39 UTC, merged